

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import Providers from "@/components/Providers/Providers";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="transition-colors duration-300 bg-white dark:bg-gray-900 text-black dark:text-white">
        <Providers>
          <Navbar />
          <div className="container mx-auto pt-6">
            <Toaster />
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}